name: flutter_emoji_keyboard
description: A Fast and Light ⚡ Emoji Keyboard ✨ Widget (implements compatible emoji support)
version: 0.1.3
homepage: https://github.com/i-Naji/emoji_keyboard

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: ^2.0.0

dev_dependencies:
  pedantic: ^1.0.0
  flutter_test:
    sdk: flutter



flutter:
  # https://flutter.dev/custom-fonts/#from-packages
